animal:
  catNames:
    - Мурзик
    - Васька
    - Матроскин
  dogNames:
    - Жучка
    - Дружок
    - Бобик
  sharkNames:
    - Аква
    - Шарки
    - Волна
  wolfNames:
    - Клык
    - Волчок
    - Серый
